
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ZH
 */
public class BurgerFrame extends javax.swing.JFrame {

    /**
     * Creates new form BurgerFrame
     */
    DisplayFrame dp=new DisplayFrame();
    SearchFrame sf = new SearchFrame(this);
    DefaultComboBoxModel<Double> dcm = new DefaultComboBoxModel<>();
    DeleteFrame del=new DeleteFrame();
    public BurgerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BurgerType_TF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Sauce_TF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Calorie_TF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Price_TF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        displayBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        order_TF = new javax.swing.JTextField();
        msg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Meal Addition Application");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 280, 30));

        jLabel2.setText("Burger Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 20));
        getContentPane().add(BurgerType_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, -1));

        jLabel3.setText("Sauce:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 40, -1));

        Sauce_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sauce_TFActionPerformed(evt);
            }
        });
        getContentPane().add(Sauce_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 20));

        jLabel4.setText("Calorie:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 20));
        getContentPane().add(Calorie_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 80, 30));

        jLabel5.setText("Price:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        getContentPane().add(Price_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 70, 30));

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        clearBTN.setText("CLEAR");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel6.setText("Operations");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 70, 30));

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        getContentPane().add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, -1));

        jLabel7.setText("Order:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));
        getContentPane().add(order_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 70, -1));
        getContentPane().add(msg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        
        
        String Type,sauce;
        double cal;
        double price;
        int order;
        String portion=null;
        String h=null;
        
        Type = BurgerType_TF.getText();
        sauce=Sauce_TF.getText();
        cal=Double.parseDouble(Calorie_TF.getText());
               
        price=Double.parseDouble(Price_TF.getText());
        
        order=Integer.parseInt(order_TF.getText());
        
        if(Type.equals("Chicken")){
        
        ChickenBurger o1=new ChickenBurger(Type,sauce,cal,price,order,portion,h);
        o1.HealthyStatus();
        o1.orderString();
        o1.addtax();
        boolean val=BulgurKingSys.addBurger(o1);
        if(val)
            msg_label.setText("Menu Added");
        else
            msg_label.setText("Menu is already added");
        
        }
        if(Type.equals("Vegetable")){

        VegetableBurger o2=new VegetableBurger(Type,sauce,cal,price,order,h);
        o2.HealthyStatus();
        o2.addtax();
        boolean val1=BulgurKingSys.addBurger(o2);
        if(val1)
            msg_label.setText("Menu Added");
        else
            msg_label.setText("Menu is already added");
        }
             
        
        

    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        dp.setDisplayTA(BulgurKingSys.displayWithString());
        dp.setVisible(true);
    }//GEN-LAST:event_displayBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        BurgerType_TF.setText("");
        Sauce_TF.setText("");
        Calorie_TF.setText("");
        Price_TF.setText("");
        order_TF.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void Sauce_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sauce_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sauce_TFActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        ArrayList arr = new ArrayList();
        sf.getCmbPrice().removeAllItems();
        for (int i = 0; i < BulgurKingSys.menulist.size(); i++) {
           BulgurKing a = BulgurKingSys.menulist.get(i);
          dcm.addElement(a.getPrice());
        }
        
        sf.getCmbPrice().setModel(dcm);
        
        
        
        
        sf.setVisible(true);
    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        ArrayList arr = new ArrayList();
        del.getCmbPrice().removeAllItems();
        for (int i = 0; i < BulgurKingSys.menulist.size(); i++) {
           BulgurKing a = BulgurKingSys.menulist.get(i);
          dcm.addElement(a.getPrice());
        }
        
        del.getCmbPrice().setModel(dcm);
        
        
        del.setVisible(true);
    }//GEN-LAST:event_deleteBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BurgerType_TF;
    private javax.swing.JTextField Calorie_TF;
    private javax.swing.JTextField Price_TF;
    private javax.swing.JTextField Sauce_TF;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel msg_label;
    private javax.swing.JTextField order_TF;
    private javax.swing.JButton searchBTN;
    // End of variables declaration//GEN-END:variables
}
